
sonar.projectKey=Proyecto-Integrador-2026-2_ClicHogar
sonar.organization=proyecto-integrador-2026-2

sonar.sources=frontend/src,backend

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,dist/**,frontend/.astro/**,backend/drizzle/**